### ISSUE TITLE
노트 앱 UX 건의사항

### ISSUE THREAD

**Issue by Jeong-Rae** [LC-02s/PBL-Notes#3]
- 노트 폴더를 만들어야 새 글쓰기가 가능한 사항
> 노트가 처음에 만들어지지 않아 버그인 줄 알았습니다. 신규폴더를 만들어야 한다는 사실이 쉽게 표시되면 좋을 것 같습니다.

- 색상 테마 변경 버튼
> 처음에 볼때는 Light 테마 아이콘이 환경설정 아이콘 처럼 보이는 것 같습니다. 개선되면 좋을 것 같습니다.

**Comment by LC-02s** [comment]
1. 초기 폴더 생성 
저도 만들면서 이 부분에 대한 고민이 조금 있었습니다
이 프로젝트 레퍼런스가 애플 노트 앱이어서 더욱 고민했던 거 같습니다
애플 특유의 처음에는 불친절하지만 적응되면 편한 UX를 염두에 두면서도 그럼에도 이 부분은 UX 적으로 문제가 있을 거 같다고 생각해서 처음에 생각했던 게 처음 시작한 유저를 대상으로 튜토리얼 느낌의 가이드 UI 제작을 고려하고 있었습니다
하지만 예상보다 구현이 복잡했고 시간적인 문제 또한 겹치면서 결과적으로 구름톤 트레이닝 플레이어 및 관계자분들이 배포 대상이셔서 이 정도는 허용해도 될 거 같다는 생각이었는데 제 생각이 안일했던 것 같네요
가이드 UI는 조금 더 구상해보고 추가하겠습니다

2. 테마 변경 버튼
테마 아이콘이 환경설정 아이콘이랑 겹쳐 보이는 건 만들면서 생각도 못 했었는데 다시 보니 진짜 설정 버튼으로 보이네요
이 부분도 조금 더 고민해 보고 수정해 보겠습니다

시간 내주셔서 감사드립니다!

**Comment by LC-02s** [comment]
1. 초기 폴더 생성 
저도 만들면서 이 부분에 대한 고민이 조금 있었습니다
이 프로젝트 레퍼런스가 애플 노트 앱이어서 더욱 고민했던 거 같습니다
애플 특유의 처음에는 불친절하지만 적응되면 편한 UX를 염두에 두면서도 그럼에도 이 부분은 UX 적으로 문제가 있을 거 같다고 생각해서 처음에 생각했던 게 처음 시작한 유저를 대상으로 튜토리얼 느낌의 가이드 UI 제작을 고려하고 있었습니다
하지만 예상보다 구현이 복잡했고 시간적인 문제 또한 겹치면서 결과적으로 구름톤 트레이닝 플레이어 및 관계자분들이 배포 대상이셔서 이 정도는 허용해도 될 거 같다는 생각이었는데 제 생각이 안일했던 것 같네요
가이드 UI는 조금 더 구상해보고 추가하겠습니다

2. 테마 변경 버튼
테마 아이콘이 환경설정 아이콘이랑 겹쳐 보이는 건 만들면서 생각도 못 했었는데 다시 보니 진짜 설정 버튼으로 보이네요
이 부분도 조금 더 구상해 보고 수정해 보겠습니다

시간 내주셔서 감사드립니다!

**Comment by LC-02s** [comment]
조금 더 고민해 본 결과 가이드 UI를 따로 제작하는 것 보다는 귀속되는 폴더 없이도 노트를 만들 수 있으면 해결되는 문제라고 판단되어 새로 배포한 버전에서는 폴더 없이 노트를 생성할 수 있게 수정하였습니다

테마 변경 버튼은 설정 아이콘과 겹쳐 보일 수 있을 거 같지만 그것 또한 유저가 테마 기능을 사용할 수 있게 유도할 수 있는 기회라고 생각되어 수정하지 않기로 하였습니다

좋은 의견 감사드립니다!
